"""QLoRA trainer: parameter-efficient fine-tuning of LLMs with 4-bit quantisation."""

from typing import Dict, List, Optional


class QLoRATrainer:
    """Fine-tunes a causal LLM using QLoRA (4-bit + LoRA adapters).

    This class wraps the HuggingFace *PEFT* and *trl* libraries to provide a
    convenient interface for supervised fine-tuning or DPO training on
    preference data generated by :class:`~src.training.SignalGenerator`.
    """

    def __init__(
        self,
        base_model: str = "mistralai/Mistral-7B-Instruct-v0.2",
        output_dir: str = "data/checkpoints",
        num_train_epochs: int = 3,
        per_device_train_batch_size: int = 4,
        learning_rate: float = 2e-4,
        lora_r: int = 16,
        lora_alpha: int = 32,
        lora_dropout: float = 0.05,
    ):
        self.base_model = base_model
        self.output_dir = output_dir
        self.num_train_epochs = num_train_epochs
        self.per_device_train_batch_size = per_device_train_batch_size
        self.learning_rate = learning_rate
        self.lora_r = lora_r
        self.lora_alpha = lora_alpha
        self.lora_dropout = lora_dropout

    def _build_lora_config(self):
        from peft import LoraConfig, TaskType

        return LoraConfig(
            r=self.lora_r,
            lora_alpha=self.lora_alpha,
            lora_dropout=self.lora_dropout,
            bias="none",
            task_type=TaskType.CAUSAL_LM,
        )

    def _build_bnb_config(self):
        import torch
        from transformers import BitsAndBytesConfig

        return BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
        )

    def train(self, train_data: List[Dict], eval_data: Optional[List[Dict]] = None):
        """Fine-tune the base model on *train_data*.

        Args:
            train_data: A list of training examples, each with ``"prompt"``,
                ``"chosen"``, and ``"rejected"`` keys.
            eval_data: Optional evaluation set in the same format.
        """
        from datasets import Dataset
        from peft import get_peft_model, prepare_model_for_kbit_training
        from transformers import AutoModelForCausalLM, AutoTokenizer, TrainingArguments
        from trl import SFTTrainer

        tokenizer = AutoTokenizer.from_pretrained(self.base_model)
        model = AutoModelForCausalLM.from_pretrained(
            self.base_model, quantization_config=self._build_bnb_config()
        )
        model = prepare_model_for_kbit_training(model)
        model = get_peft_model(model, self._build_lora_config())

        train_dataset = Dataset.from_list(train_data)
        eval_dataset = Dataset.from_list(eval_data) if eval_data else None

        training_args = TrainingArguments(
            output_dir=self.output_dir,
            num_train_epochs=self.num_train_epochs,
            per_device_train_batch_size=self.per_device_train_batch_size,
            learning_rate=self.learning_rate,
            save_strategy="epoch",
            evaluation_strategy="epoch" if eval_dataset else "no",
            logging_steps=10,
            fp16=True,
        )

        trainer = SFTTrainer(
            model=model,
            args=training_args,
            train_dataset=train_dataset,
            eval_dataset=eval_dataset,
            tokenizer=tokenizer,
            dataset_text_field="chosen",
        )

        trainer.train()
        trainer.save_model(self.output_dir)
